# Generated by Django 6.1.1 on 2026-09-28 05:50

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('image', models.ImageField(upload_to='history/campus/', validators=[core.validators.validate_image_file])),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Campus photos',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
