# Generated by Django 6.1.1 on 2026-09-26 09:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='map_coordinates',
            field=models.CharField(blank=True, help_text='The school\'s exact spot, for the map on the Contact page. In Google Maps, press and hold (or right-click) on the school and copy the two numbers shown, e.g. "-6.13834, 35.74642".', max_length=60, validators=[core.validators.validate_map_coordinates]),
        ),
    ]
